version: "3.8"

services:
  app:
    build: .
    image: notificationservice:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 502291
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - product-network
networks:
  product-network:
    driver: bridge